name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: output
      - uses: Platane/snk@master
        with:
          github_user_name: hakikyy
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
            dist/ocean.gif
      - run: git add .
      - run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit -m "Generate Snake" || echo "No changes to commit"
      - run: git push